### ISSUE TITLE
[Error]  Bearer JWT Token 통신 에러 공유

### ISSUE THREAD

**Issue by tape22** [YAPP-18th/Web-Team-1-Backend#36]
nested exception is io.jsonwebtoken.MalformedJwtException: Unable to read JSON value: �z��&�r#�$�3S"] with root cause

회고글 저장하는 POST method 통신 시 다음과 같은 에러를 내면서 서버 500 에러가 났습니다. 찾아보니 유효하지 않은 문장의 jwt 토큰 값이 넘어와서 생기는 오류로, 프론트에서 token값을 보낼 때 Bearer을 지우고 "jwt 토큰 값"만 보내니 통신이 완료되었습니다. 

@Authorization 으로 헤더에 있는 토큰을 직접 가져와서 userIdx를 얻기 전에는 프론트에서 Bearer + jwt 토큰을 보내줘야 통신이 되었었는데, 코드가 변경된 이후로는 jwt 토큰만을 입력해야 통신이 되어서 왜 그런지는 댓글로 찾아서 달아놓겠습니다.

**Comment by ybell1028** [comment]
```.java
    public ResponseEntity<Object> getProfiles(HttpServletRequest request){
        String token = tokenService.getTokenFromRequest(request);
        Long userIdx = tokenService.getUserIdx(token);
```
@RequestHeader 어노테이션 쓰지 마시고 HttpServletRequest에서 헤더 토큰 추출하는 메소드 사용하면 됩니다!

**Comment by ybell1028** [comment]
해결 된 것 같으니 이슈 닫겠습니다~
